### ISSUE TITLE
Problems compiling nuBASIC 1.51 on Debian 10.1

### ISSUE THREAD

**Issue by programandala-net** [eantcal/nubasic#2]
Hello.

nuBASIC seems great, and I want to try it, especially because the nuBASIC programs could run on Android as well, with Termux. It could be a good option for a text console project of mine.

But I'm having problems with the compilation:

When I executed <./configure> in order to prepare the compilation of nuBASIC 1.51 I got:

> configure: error: cannot find install-sh, install.sh, or shtool in "./" "./.." "./../.."

After a bit DuckDuckGoing, I found a solution: execute `autoreconf -i` first, which produced the following output:

> configure.ac:17: installing './compile'
> configure.ac:20: installing './config.guess'
> configure.ac:20: installing './config.sub'
> configure.ac:6: installing './install-sh'
> configure.ac:6: installing './missing'
> configure.ac:212: error: required file 'ide/gtk/mipjson/miptknzr/lib/Makefile.in' not found
> configure.ac:212: error: required file 'ide/gtk/mipjson/lib/Makefile.in' not found
> configure.ac:212: error: required file 'ide/gtk/Makefile.in' not found
> Makefile.am: installing './depcomp'
> autoreconf: automake failed with exit status: 1

Despite the exit status, then "configure" worked at last, though it failed at the end:

> checking for strerror... yes
> checking whether compiling gtkide... no
> checking whether compiling tinyver... no
> checking for xterm... no
> configure: WARNING: Please install xterm for graphical programs.
> checking for gnome-terminal... no
> configure: error: Please install xterm or gnome-terminal before install

I guessed that was about 256-color support. I use GNU Screen on lxterminal. I restarted with rxvt instead and I got this at the end:

> checking for xterm... yes
> configure: WARNING: Please install xterm for graphical programs.
> checking for xmessage... yes
> checking for X... libraries , headers
> checking for XDrawLine in -lX11... yes
> checking whether compiling sdl2... no
> checking for aplay... (cached) yes
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating lib/Makefile
> config.status: creating config.h
> config.status: executing depfiles commands

There was still a warning about xterm, but It seemed fine (I tried also with (u)xterm, tilda and other terminal emulators, but no difference).

But "make" only displayed this and halted:

> Makefile:511: .deps/main.Po: No existe el fichero o el directorio
> make: *** No hay ninguna regla para construir el objetivo '.deps/main.Po'.  Alto.

Effectively, there's no ".deps" directory.

It seems I'm missing something. Any clue?

Thank you

**Comment by eantcal** [comment]
Hi Marcos. Sorry for the late reply. I am abroad now. Just a tip on the
fly. I have added support for cmake and I was to remove the autotool
support. You can try with cmake. It should work. I will provide you
further details once back in Dublin.
Thank you very much.
Antonino

**Comment by programandala-net** [comment]
Thanks, cmake works fine. I have compiled 1.51. Meanwhile, I had installed 1.50 with the DEB archive.

**Comment by eantcal** [comment]
Cool!

Best,
Antonino
